[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-select = ["I"]       # activa reglas de imports (isort)
ignore        = ["E203"]    # excepción que rompe Black

# 👉 tabla hija (no inline) para los ignores por archivo
[tool.ruff.lint.per-file-ignores]
"app/db/base.py"          = ["F401"]
"app/models/__init__.py"  = ["F401"]
"scripts/db_check.py"     = ["F401"]
"migrations/env.py"       = ["E402", "I001"]
