"""Añade campos para flujo de pago y derivacion

Revision ID: 370da63568d7
Revises: 4abeebed31aa
Create Date: 2025-06-23 22:42:22.890271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '370da63568d7'
down_revision: Union[str, Sequence[str], None] = '4abeebed31aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisements', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(op.f('advertisements_ibfk_1'), 'advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements', 'companies', ['company_id'], ['id'])
    op.alter_column('close_reasons', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(op.f('close_reasons_ibfk_1'), 'close_reasons', type_='foreignkey')
    op.create_foreign_key(None, 'close_reasons', 'companies', ['company_id'], ['id'])
    op.add_column('media_files', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('media_files', sa.Column('url', sa.String(length=500), nullable=False))
    op.add_column('media_files', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('media_files', sa.Column('advertisement_id', sa.Integer(), nullable=True))
    op.alter_column('media_files', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(op.f('media_files_ibfk_1'), 'media_files', type_='foreignkey')
    op.create_foreign_key(None, 'media_files', 'advertisements', ['advertisement_id'], ['id'])
    op.create_foreign_key(None, 'media_files', 'companies', ['company_id'], ['id'])
    op.drop_column('media_files', 'is_active')
    op.drop_column('media_files', 'file_url')
    op.drop_column('media_files', 'description')
    op.drop_column('media_files', 'media_type')
    op.add_column('services', sa.Column('requires_payment', sa.Boolean(), nullable=False))
    op.alter_column('services', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(op.f('services_ibfk_1'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'companies', ['company_id'], ['id'])
    op.add_column('tickets', sa.Column('original_service_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('derivation_count', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('processed_by_cashier_id', sa.Integer(), nullable=True))
    op.alter_column('tickets', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tickets', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tickets', 'service_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(op.f('tickets_ibfk_1'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_ibfk_3'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_ibfk_2'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'close_reasons', ['close_reason_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['processed_by_cashier_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'services', ['original_service_id'], ['id'])
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.alter_column('users', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_ibfk_2'), 'tickets', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('tickets_ibfk_3'), 'tickets', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('tickets_ibfk_1'), 'tickets', 'close_reasons', ['close_reason_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tickets', 'service_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('tickets', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('tickets', 'processed_by_cashier_id')
    op.drop_column('tickets', 'derivation_count')
    op.drop_column('tickets', 'original_service_id')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_ibfk_1'), 'services', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('services', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('services', 'requires_payment')
    op.add_column('media_files', sa.Column('media_type', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('media_files', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('media_files', sa.Column('file_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('media_files', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.create_foreign_key(op.f('media_files_ibfk_1'), 'media_files', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('media_files', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('media_files', 'advertisement_id')
    op.drop_column('media_files', 'duration_seconds')
    op.drop_column('media_files', 'url')
    op.drop_column('media_files', 'file_type')
    op.drop_constraint(None, 'close_reasons', type_='foreignkey')
    op.create_foreign_key(op.f('close_reasons_ibfk_1'), 'close_reasons', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('close_reasons', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.create_foreign_key(op.f('advertisements_ibfk_1'), 'advertisements', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('advertisements', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
