"""add tickets relationship to Company

Revision ID: 4abeebed31aa
Revises: d8e2e6da1430
Create Date: 2025-06-18 22:51:11.855016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abeebed31aa'
down_revision: Union[str, Sequence[str], None] = 'd8e2e6da1430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
