"""Add service relation to User and ticket updates

Revision ID: 91f40deed950
Revises: 370da63568d7
Create Date: 2025-06-26 23:16:07.841978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91f40deed950'
down_revision: Union[str, Sequence[str], None] = '370da63568d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('attended_by_id', sa.Integer(), nullable=True))
    op.alter_column('tickets', 'call_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'tickets', 'users', ['attended_by_id'], ['id'])
    op.add_column('users', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'service_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.alter_column('tickets', 'call_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('tickets', 'attended_by_id')
    # ### end Alembic commands ###
