"""Update media_files table for multimedia management

Revision ID: aa15a4200442
Revises: 91f40deed950
Create Date: 2025-07-01 14:27:45.501594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa15a4200442'
down_revision: Union[str, Sequence[str], None] = '91f40deed950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('media_files', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('media_files', sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('media_files', 'url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('media_files', 'duration_seconds',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               nullable=False)
    op.create_index(op.f('ix_media_files_company_id'), 'media_files', ['company_id'], unique=False)
    op.drop_constraint(op.f('media_files_ibfk_1'), 'media_files', type_='foreignkey')
    op.drop_column('media_files', 'advertisement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('advertisement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('media_files_ibfk_1'), 'media_files', 'advertisements', ['advertisement_id'], ['id'])
    op.drop_index(op.f('ix_media_files_company_id'), table_name='media_files')
    op.alter_column('media_files', 'duration_seconds',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               nullable=True)
    op.alter_column('media_files', 'url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('media_files', 'date_create')
    op.drop_column('media_files', 'status')
    op.drop_column('media_files', 'name')
    # ### end Alembic commands ###
