"""Remove relationship from Advertisement to MediaFile

Revision ID: fff4743cff36
Revises: aa15a4200442
Create Date: 2025-07-01 16:31:22.894410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fff4743cff36'
down_revision: Union[str, Sequence[str], None] = 'aa15a4200442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('advertisements', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('advertisements', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index(op.f('ix_advertisements_company_id'), 'advertisements', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisements_company_id'), table_name='advertisements')
    op.alter_column('advertisements', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('advertisements', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('advertisements', 'date_create')
    # ### end Alembic commands ###
