name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Provide test .env
        run: cp .env.example .env

      - uses: actions/checkout@v4
      - name: Provide test .env
        run: cp .env.example .env
      - uses: actions/setup-python@v5
        with:
         python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install ruff pytest

      - name: Lint
        run: ruff check .

      - name: Tests
        run: pytest -q
